name: dfi_flutter_admin_panel
description: "A new Flutter project."
publish_to: 'none'

version: '3.1.0'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ^3.29.0
  
dependencies:


  flutter_localization: ^0.3.0
  flutter:
    sdk: flutter

  http: ^1.1.0
  convert: ^3.1.1

  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  provider: ^6.1.2
  dropdown_button2: ^2.3.9
  country_flags: ^3.1.0
  iconly: ^1.0.1
  flutter_svg: ^2.0.16
  material_design_icons_flutter: ^7.0.7296
  expansion_widget: ^0.1.0
  syncfusion_flutter_charts: ^28.1.33
  go_router: ^14.6.2
  fl_chart: ^0.70.2
  collection: ^1.18.0
  flutter_layout_grid: ^2.0.7
  syncfusion_flutter_calendar: ^28.1.33
  intl: ^0.19.0
  feather_icons: ^1.2.0
  flutter_animate: ^4.5.2
  table_calendar: ^3.1.3
  syncfusion_flutter_datagrid: ^28.1.33
  magicoon_icons: ^0.0.5
  flex_color_picker: ^3.6.0
  google_maps_flutter_web: ^0.5.10
  google_maps_flutter: ^2.10.0
  iconsax_plus: ^1.0.0
  syntax_highlight: ^0.4.0
  url_strategy: ^0.3.0
  pdf: ^3.11.1
  printing: ^5.13.4
  timeline_tile: ^2.0.0


  # Remote Packages
  appflowy_board:
    # path: ../appflowy-board/
    git:
      url: https://github.com/iamtoricool/appflowy-board.git
      ref: main

  responsive_grid:
    git: 
      url: https://github.com/iamtoricool/ResponsiveGrid_Flutter.git
      ref: master



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/widget_images/
    - assets/images/widget_images/banner_images/
    - assets/images/sidebar_icons/
    - assets/images/widget_images/dashboard_icon/
    - assets/images/widget_images/card_images/feature_card/
    - assets/images/widget_images/sm_icon/
    - assets/images/widget_images/authentication_images/
    - assets/images/widget_images/dashboard_overview_icon/
    - assets/images/widget_images/svg_icons/
    - assets/images/widget_images/not_found_images/
    - assets/app_icons/
    - assets/images/widget_images/dashboard_overview_icon/ecommerce_admin_icons/
    - assets/images/widget_images/dashboard_overview_icon/ecommerce_admin_icons/category_icons/
    - assets/images/widget_images/dashboard_overview_icon/influencer_admin_icons/
    - assets/images/widget_images/dashboard_overview_icon/news_admin_icons/
    # static images
    - assets/images/static_images/
    - assets/images/static_images/ai_generated/images/
    - assets/images/static_images/avatars/person_images/
    - assets/images/static_images/avatars/placeholder_avatar/
    - assets/images/static_images/background_images/
    - assets/images/static_images/icons/crypto_icons/
    - assets/images/static_images/placeholder_images/random_placeholders/
    - assets/images/static_images/product_images/
    #socail icons
    - assets/images/static_images/icons/social_icons/
  #   - images/a_dot_ham.jpeg
    #country image
    - assets/images/widget_images/country_image/
    - assets/images/widget_images/delivery_dashboard_icons/
    - assets/images/widget_images/dashboard_lms_management_icons/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter/Inter-Black.ttf
          weight: 900

flutter_intl:
  enabled: true