class DemoProduct {
  final String id;
  final String image;
  final String code;
  final String name;
  final String category;
  final String brand;
  final String unit;
  final String qty;
  bool isSelected = false;
  final String purchasePrice;
  final String salesPrice;
  final String type;

  DemoProduct(
      {required this.id,
      required this.image,
      required this.code,
      required this.name,
      required this.category,
      required this.brand,
      required this.unit,
      required this.qty,
      required this.purchasePrice,
      required this.salesPrice,
      required this.type});

  @override
  String toString() =>
      'DataModel(image: $image, code: $code, name: $name, category: $category, brand: $brand, unit: $unit, qty:$qty, purchasePrice: $purchasePrice, salesPrice: $salesPrice, type: $type,)';
}

class Product {
  static List<DemoProduct> allProduct = [
    DemoProduct(
      id: '1',
      image: 'assets/images/static_images/product_images/product_image_24.png',
      code: 'Ph2563',
      name: 'All Natural Italian-Style \nChicken Meatballs',
      category: 'Fruits',
      brand: 'N/A',
      unit: 'Kg',
      qty: '50',
      purchasePrice: '\$0',
      salesPrice: '\$0',
      type: 'Single',
    ),
    DemoProduct(
      id: '2',
      image: 'assets/images/static_images/product_images/product_image_22.png',
      code: 'Ph2463',
      name: 'Headphone',
      category: 'Food',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '50',
      purchasePrice: '\$50',
      salesPrice: '\$60',
      type: 'Variant',
    ),
    DemoProduct(
      id: '3',
      image: 'assets/images/static_images/product_images/product_image_02.png',
      code: 'Ph2543',
      name: 'Smarts Watch',
      category: 'Fashion',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '50',
      purchasePrice: '\$20',
      salesPrice: '\$30',
      type: 'Single',
    ),
    DemoProduct(
      id: '4',
      image: 'assets/images/static_images/product_images/product_image_21.png',
      code: 'Ph2564',
      name: 'Best Bluetooth Headphone',
      category: 'Computers',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$0',
      salesPrice: '\$50',
      type: 'Single',
    ),
    DemoProduct(
      id: '5',
      image: 'assets/images/static_images/product_images/product_image_08.png',
      code: 'Ph1563',
      name: 'All Natural Italian-Style \nChicken Meatballs',
      category: 'Shoes',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$400',
      salesPrice: '\$500',
      type: 'Variant',
    ),
    DemoProduct(
      id: '6',
      image: 'assets/images/static_images/product_images/product_image_18.jpeg',
      code: 'Ph2163',
      name: 'Lemon Cream Crunch Cookies',
      category: 'Beauty',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$80',
      salesPrice: '\$30',
      type: 'Variant',
    ),
    DemoProduct(
      id: '7',
      image: 'assets/images/static_images/product_images/product_image_17.png',
      code: 'Ph2513',
      name: 'Organic Sweet Lime \n/ Mosambi',
      category: 'Sports',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$80',
      salesPrice: '\$90',
      type: 'Single',
    ),
    DemoProduct(
      id: '8',
      image: 'assets/images/static_images/product_images/product_image_16.png',
      code: 'Ph2561',
      name: 'Apple iPhone 11 64GB \nYellow Fully Unlocked',
      category: 'Electronic',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$400',
      salesPrice: '\$400',
      type: 'Variant',
    ),
    DemoProduct(
      id: '9',
      image: 'assets/images/static_images/product_images/product_image_19.png',
      code: 'Ph2563',
      name: 'Organic Green Seedless Grapes',
      category: 'Electronic',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$400',
      salesPrice: '\$400',
      type: 'Variant',
    ),
    DemoProduct(
      id: '10',
      image: 'assets/images/static_images/product_images/product_image_21.png',
      code: 'Ph2563',
      name: 'All Natural Italian-Style Chicken Meatballs',
      category: 'Electronic',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$400',
      salesPrice: '\$400',
      type: 'Single',
    ),
    DemoProduct(
      id: '11',
      image: 'assets/images/static_images/product_images/product_image_24.png',
      code: 'Ph2563',
      name: 'All Natural Italian-Style \nChicken Meatballs',
      category: 'Fruits',
      brand: 'N/A',
      unit: 'Kg',
      qty: '50',
      purchasePrice: '\$09',
      salesPrice: '\$32',
      type: 'Variant',
    ),
    DemoProduct(
      id: '12',
      image: 'assets/images/static_images/product_images/product_image_22.png',
      code: 'Ph2563',
      name: 'Headphone',
      category: 'Food',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '50',
      purchasePrice: '\$70',
      salesPrice: '\$52',
      type: 'Variant',
    ),
    DemoProduct(
      id: '13',
      image: 'assets/images/static_images/product_images/product_image_02.png',
      code: 'Ph2563',
      name: 'Smarts Watch',
      category: 'Fashion',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '50',
      purchasePrice: '\$80',
      salesPrice: '\$120',
      type: 'Single',
    ),
    DemoProduct(
      id: '14',
      image: 'assets/images/static_images/product_images/product_image_21.png',
      code: 'Ph2563',
      name: 'Best Bluetooth Headphone',
      category: 'Computers',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '15',
      purchasePrice: '\$70',
      salesPrice: '\$07',
      type: 'Variant',
    ),
    DemoProduct(
      id: '15',
      image: 'assets/images/static_images/product_images/product_image_08.png',
      code: 'Ph2563',
      name: 'All Natural Italian-Style \nChicken Meatballs',
      category: 'Shoes',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$10',
      salesPrice: '\$20',
      type: 'Single',
    ),
    DemoProduct(
      id: '16',
      image: 'assets/images/static_images/product_images/product_image_18.jpeg',
      code: 'Ph2563',
      name: 'Lemon Cream Crunch Cookies',
      category: 'Beauty',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$40',
      salesPrice: '\$0',
      type: 'Variant',
    ),
    DemoProduct(
      id: '17',
      image: 'assets/images/static_images/product_images/product_image_17.png',
      code: 'Ph2563',
      name: 'Organic Sweet Lime \n/ Mosambi',
      category: 'Sports',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$10',
      salesPrice: '\$20',
      type: 'Single',
    ),
    DemoProduct(
      id: '18',
      image: 'assets/images/static_images/product_images/product_image_16.png',
      code: 'Ph2563',
      name: 'Apple iPhone 11 64GB \nYellow Fully Unlocked',
      category: 'Electronic',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$400',
      salesPrice: '\$400',
      type: 'Variant',
    ),
    DemoProduct(
      id: '19',
      image: 'assets/images/static_images/product_images/product_image_19.png',
      code: 'Ph2563',
      name: 'Organic Green Seedless Grapes',
      category: 'Electronic',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$400',
      salesPrice: '\$400',
      type: 'Single',
    ),
    DemoProduct(
      id: '20',
      image: 'assets/images/static_images/product_images/product_image_21.png',
      code: 'Ph2563',
      name: 'All Natural Italian-Style \nChicken Meatballs',
      category: 'Electronic',
      brand: 'N/A',
      unit: 'Pcs',
      qty: '5',
      purchasePrice: '\$400',
      salesPrice: '\$400',
      type: 'Variant',
    )
  ];
}
