class DemoDataPurchase {
  final String id;
  final String date;
  final String invoice;
  final String supplierName;
  final String warehouse;
  final String grandTotal;
  final String paid;
  final String due;

  bool isSelected = false;
  final String paymentType;
  final String paymentStatus;
  final String salesBy;

  DemoDataPurchase(
      {required this.id,
      required this.date,
      required this.invoice,
      required this.supplierName,
      required this.warehouse,
      required this.grandTotal,
      required this.paid,
      required this.due,
      required this.paymentType,
      required this.paymentStatus,
      required this.salesBy});

  @override
  String toString() =>
      'DataModel(date: $date, invoice: $invoice, supplierName: $supplierName, warehouse: $warehouse, grandTotal: $grandTotal, paid: $paid, due:$due, paymentType: $paymentType, paymentStatus: $paymentStatus, salesBy: $salesBy,)';
}

class AllPurchase {
  static List<DemoDataPurchase> allPurchase = [
    DemoDataPurchase(
      id: '1',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Partial',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '2',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Bessie Cooper',
      warehouse: 'Evolution Fulfillment',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '3',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Arlene McCoy',
      warehouse: 'FM logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '4',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Ralph Edwards',
      warehouse: 'EPT Global Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Partial',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '5',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Ralph Edwards',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '6',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Ralph Edwards',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '7',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '8',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '9',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '10',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Arlene McCoy',
      warehouse: 'Warehouse 5',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '11',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '12',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Arlene McCoy',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '13',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '14',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Arlene McCoy',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '15',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '16',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Arlene McCoy',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '17',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Arlene McCoy',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '18',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '19',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Arlene McCoy',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '20',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '21',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '22',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '23',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '24',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '25',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '26',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '27',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '28',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '29',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '30',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '31',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '32',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '33',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '34',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '35',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '36',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '37',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '38',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '39',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '40',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '41',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '42',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '43',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '44',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '45',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '46',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '47',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '48',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '49',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Cash',
      paymentStatus: 'Paid',
      salesBy: 'Admin',
    ),
    DemoDataPurchase(
      id: '50',
      date: '25 jan 2024',
      invoice: 'IN255Vi',
      supplierName: 'Devon Lane',
      warehouse: 'Brite Logistics',
      grandTotal: '\$500',
      paid: '\$300',
      due: '\$200',
      paymentType: 'Bank',
      paymentStatus: 'Unpaid',
      salesBy: 'Admin',
    ),
  ];
}
